/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/Mata.glb -o src/components/MataGenerated.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Mata.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere001.geometry} material={materials['Material.006']} position={[0, 0.199, 0.745]} scale={[0.385, 0.436, 0.204]} />
      <mesh geometry={nodes.Saraf2.geometry} material={materials['Material.005']} position={[-0.138, -0.728, 0.758]} rotation={[0.034, 0.038, 1.485]} scale={[0.136, 0.136, 0.085]} />
      <mesh geometry={nodes.Saraf.geometry} material={materials['Material.005']} position={[-0.42, 0.488, 0.824]} rotation={[-0.479, 0.071, -0.697]} scale={0.164} />
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.002']} position={[0.014, 0.176, -0.211]} rotation={[-Math.PI / 2, 0, 0]} scale={1.345} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials['Material.004']} position={[0, 0.176, -0.219]} rotation={[-Math.PI / 2, 0, 0]} scale={1.345} />
      <mesh geometry={nodes.Sphere003.geometry} material={materials.Material} position={[0, 0.168, -0.276]} scale={1.301} />
      <mesh geometry={nodes.Sphere004.geometry} material={nodes.Sphere004.material} position={[0, 0.15, -0.241]} rotation={[-Math.PI / 2, 0, 0]} scale={1.156} />
      <mesh geometry={nodes.Sphere005.geometry} material={materials['Material.003']} position={[0, 0.15, -0.241]} rotation={[-Math.PI / 2, 0, 0]} scale={1.156} />
      <mesh geometry={nodes.BezierCurve009.geometry} material={materials['Material.007']} position={[-0.831, 1.041, -0.538]} rotation={[1.006, 0, -1.553]} scale={0.181} />
      <mesh geometry={nodes.BezierCurve.geometry} material={materials['Material.007']} position={[0, -0.026, -0.964]} scale={0.427} />
      <mesh geometry={nodes.Sphere006.geometry} material={materials['Material.009']} position={[0, 0.199, 0.745]} scale={[0.385, 0.436, 0.204]} />
    </group>
  )
}

useGLTF.preload('/Mata.glb')
